#+OPTIONS: toc:nil
#+TITLE: Orientierungsstage

* Montag
ich bin mit meinen Eltern den Sky Tower hoch.
Das sah schon sehr cool aus Auckland aus über 300m zu sehen.

* Dienstag
Wegen dem Regenwetter sind wir zusammen in das Auckland War Memorial Museum gegangen.
Das liegt in einem wunderschönen Park, den wir uns aber wegen dem Wetter leider nicht anschauen konnten.
Das Museum selbst bietet sehr vielfältige Informationen.
Auf dem Erdgeschoss steht ein bisschen was zur Geschichte von Auckland und über die Boote der Maori.
Der erste Stock enthält viel über Natur und Vulkane.
Lediglich auf dem 2.Stock steht etwas über die militärische Geschichte.
Es werden dort verschiedene asiatische Konflikte, Bürgerkriege und im speziellen die Rolle von Neuseeland im 1. und 2.Weltkrieg beschrieben.
Das bin ich in einer Uniform aus dem 1.Weltkrieg.
Am Abend bin ich mit Leuten aus dem Hostel in ne Bar gegangen.
Da haben wir Pool gespielt.

* Mittwoch
An dem Tag hab ich Vorbereitungen fürs Campen getroffen.
Als erstes hab ich mir Kompressionsbeutel gekauft, in die ich dann auch gleich ein Teil meiner Klamotten verstaut habe.
Dabei war ich schon ziemlich überrascht wie viel das bringt an Platzersparnis.
Den Platz benötige ich auch, denn ich hab mir dann in einem Secondhandshop auch noch ein Zelt und eine Schlafmatte gekauft und bin damit bereit übers Wochenende auf Waiheke-Island campen zu gehen.
Am Abend hab ich noch mit der Gruppe die ich getroffen hab, an dem Bar Crawl teilgenommen.
Da besucht man mehrere Bars und und kriegt überall einen free drink.
Das hat super Spaß gemacht.
Die erste Bar war hat ein bisschen langsam gestartet aber dann die zweite Bar war Rock 'n' Roll und danach wurde es nur besser.
Am Ende sind wir bis 2:30 in einer Art Techno-Club geblieben.

* Donnerstag
Der Tag war dann ziemlich entspannt.
Ich hab bis 12 ausgeschlafen und danach noch ein paar Sachen gekauft und schließlich noch mit anderen Gästen von dem Hostel geredet.
Das ist wirklich cool und ich glaube auch, dass mein Englisch dadurch flüssiger wird.

* Freitag
An dem Tag war morgens ein virtueller Spieleabend mit Freunden aus Deutschland.
Am Abend war wieder ein Barcrawl. Eine der Bars hatte ein Schachbrett und da habe ich mit einigen Leuten gespielt.
Das war richtig lustig, weil wir Hand und Kopf gespielt haben.
Dabei spielt man Schach zu viert.
Ein Partner ist Kopf, der sagt die Figur die gezogen wird wie "Bauer".
Der andere ist Hand und spielt den Zug, beispielsweise wählt den a Bauern und zieht 1 Feld.
Aber bei dem Crawl bin ich nur für 2 Bars geblieben, weil ich am nächsten Tag nach Waiheke-Island gefahren bin
